"""Add conversation message tool_invocation tables

Revision ID: 736cddebc5ac
Revises: 004
Create Date: 2026-01-18 21:27:24.563021+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736cddebc5ac'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolinvocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('input_params', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolinvocation_message_id'), 'toolinvocation', ['message_id'], unique=False)
    op.alter_column('message', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', name='messagerole'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(length=50000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=5000),
               existing_nullable=False)
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_constraint(op.f('message_user_id_fkey'), 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'tool_calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('message_user_id_fkey'), 'message', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.alter_column('message', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=5000),
               type_=sa.VARCHAR(length=50000),
               existing_nullable=False)
    op.alter_column('message', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=postgresql.ENUM('USER', 'ASSISTANT', name='messagerole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_toolinvocation_message_id'), table_name='toolinvocation')
    op.drop_table('toolinvocation')
    # ### end Alembic commands ###
